name: async job
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Async Job
      run: |
        sleep 10
    - name: Get latest Checks
      uses: actions/github-script@v6.4.0
      id: get-test-check-runs-id
      with:
        script: |
          const developList = await github.rest.checks.listForRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'develop',
                  check_name: 'async-job-test-develop',
                  status: 'queued',
                  filter: 'latest'
              });


          if (developList.data.check_runs.length != 0) {
              return developList.data.check_runs[0].id;
          }

          const masterList = await github.rest.checks.listForRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'master',
                  check_name: 'async-job-test-master',
                  status: 'queued',
                  filter: 'latest'
              });

          return masterList.data.check_runs[0].id;
        result-encoding: string
    - uses: LouisBrunner/checks-action@69aaabbcf32668b60dc03b65deabfe23e92d9c41
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check_id: ${{steps.get-test-check-runs-id.outputs.result}}
        status: completed
        conclusion: ${{ (steps.get-test-check-runs-id.outcome == 'success' && 'success' ) || 'failure'  }}
